config/routes.rb
Rails.application.routes.draw do
  resources :blog_posts
  resources :people
  resources :blogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_many :blog_posts

  validates :name, presence: true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  belongs_to :blog

  validates :name, presence: true
end

app/models/person.rb
class Person < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ResourcesController

  private

    def resource_params
      params.require(:blog_post).permit(:blog_id, :name, :title, :content)
    end
end

app/controllers/blogs_controller.rb
class BlogsController < ResourcesController

  private

    # Only allow a list of trusted parameters through.
    def resource_params
      params.require(:blog).permit(:name, :title, :content)
    end
end

app/controllers/people_controller.rb
class PeopleController < ResourcesController
  private

    # Only allow a list of trusted parameters through.
    def resource_params
      params.require(:person).permit(:name, :email, :age)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # initialize
  def initialize(args = {})
    super()
    @plural = self.controller_name
    @model = find_model(@plural)
    @singular = to_singular(@model)
  end

  # GET /@model
  def index
    #instance_variable_set("@#{@plural}", @model.all)
    @resources = @model.all
  end

  # GET /@model/1
  # GET /posts/1.json
  def show
  end

  # GET /@model/new
  def new
    # instance_variable_set("@#{@singular}", @model.new)
    @resource = @model.new
  end

  # GET /@model/1/edit
  def edit
  end

  # POST /@model
  def create
    #instance_variable_set("@#{@singular}", @model.new(resource_params))
    @resource = @model.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: "#{@model} was successfully created." }
        format.json { render :show, status: :created, location: @resource }
      else
        format.html { render :new }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
=begin
      if instance_variable_get("@#{@singular}").save
        format.html { redirect_to instance_variable_get("@#{@singular}"), notice: "#{@model} was successfully created." }
        format.json { render :show, status: :created, location: instance_variable_get("@#{@singular}") }
      else
        format.html { render :new }
        format.json { render json: instance_variable_get("@#{@singular}").errors, status: :unprocessable_entity }
      end
=end
    end
  end

  # PATCH/PUT /@model/1
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: "#{@model} was successfully created." }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
=begin
    respond_to do |format|
      if instance_variable_get("@#{@singular}").update(resource_params)
        format.html { redirect_to instance_variable_get("@#{@singular}"), notice: "#{@model} was successfully updated." }
        format.json { render :show, status: :ok, location: @resource }
      else
        format.html { render :edit }
        format.json { render json: instance_variable_get("@#{@singular}").errors, status: :unprocessable_entity }
      end
    end
=end
  end

  # DELETE /@model/1
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to "/#{@plural}", notice: "#{@model} was successfully destroyed." }
      format.json { head :no_content }
    end
=begin
    instance_variable_get("@#{@singular}").destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "#{@model} was successfully destroyed." }
      format.json { head :no_content }
    end
=end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @resource = @model.find(params[:id])
    end

    # find model = corresponding model
    def find_model(plural)
      Kernel.const_get(ActiveSupport::Inflector.classify(plural))
    end

    # find model = corresponding model
    def to_singular(model)
      model.name.underscore
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, local: true) do |form| %>
  <% if blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :blog_id %>
    <%= form.number_field :blog_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form', blog_post: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blog Posts</h1>

<table>
  <thead>
    <tr>
      <th>Blog</th>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |blog_post| %>
      <tr>
        <td><%= blog_post.blog_id %></td>
        <td><%= blog_post.name %></td>
        <td><%= blog_post.title %></td>
        <td><%= blog_post.content %></td>
        <td><%= link_to 'Show', blog_post %></td>
        <td><%= link_to 'Edit', edit_blog_post_path(blog_post) %></td>
        <td><form method="post" name="resouce_delete" action="/blog_posts/<%= blog_post.id %>"><input type="hidden" name="_method" value="delete" /><%= hidden_field_tag :authenticity_token, form_authenticity_token %><a href="javascript:resouce_delete.submit()">Destory</a></form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog Post', new_blog_post_path %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form', blog_post: @resource %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blog:</strong>
  <%= @resource.blog_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @resource.content %>
</p>

<%= link_to 'Edit', edit_blog_post_path(@resource) %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |blog| %>
      <tr>
        <td><%= blog.name %></td>
        <td><%= blog.title %></td>
        <td><%= blog.content %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><form method="post" name="resouce_delete" action="/blogs/<%= blog.id %>"><input type="hidden" name="_method" value="delete" /><%= hidden_field_tag :authenticity_token, form_authenticity_token %><a href="javascript:resouce_delete.submit()">Destory</a></form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @resource %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @resource.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @resource.content %>
</p>

<%= link_to 'Edit', edit_blog_path(@resource) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
        <% person.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @resource %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.email %></td>
        <td><%= person.age %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><form method="post" name="resouce_delete" action="/people/<%= person.id %>"><input type="hidden" name="_method" value="delete" /><%= hidden_field_tag :authenticity_token, form_authenticity_token %><a href="javascript:resouce_delete.submit()">Destory</a></form></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @resource %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @resource.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resource.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @resource.age %>
</p>

<%= link_to 'Edit', edit_person_path(@resource) %> |
<%= link_to 'Back', people_path %>